apiVersion: v1
kind: Service
metadata:
  name: visualizer-api-service
spec:
  type: LoadBalancer # Exposes the service externally using a cloud provider's load balancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: visualizer-api
